#!/usr/bin/env python3
"""D7 Stage 2, step B0: compile the per-cell derivatives of the axisymmetric Lagrangian for the Newton solver.
For the jet q (value, d_R, d_z of S, W_R, W_z, A, B, C, D, U_R, U_z, F; 30 entries) this compiles
  gL = dLrest/dq,  HL = d2Lrest/dq2,  gY = dY/dq,  HY = d2Y/dq2
as numpy functions of (q..., R, v_w), with common-subexpression elimination. Each (row, col) Hessian entry is
lambdified separately, so the sparsity pattern is known and zero entries cost nothing.
Output: local_derivs.py, a generated module (plain Python) imported by solve_steady.py.
"""

import json, sys, time, sympy as sp

sys.path.insert(0, "../d3_alpha")
from sym_json import dec

NAMES = ["S", "W_R", "W_z", "A", "B", "C", "D", "U_R", "U_z", "F"]
t0 = time.time()
d = json.load(open("steady_lagrangian_axisym.json"))
L, Y = dec(d["Lrest"]), dec(d["Y"])
R, vw = sp.Symbol("R", positive=True), sp.Symbol("v_w", real=True)
jet = [sp.Symbol(n + s) for n in NAMES for s in ("", "_R", "_z")]
# the reduced expressions use plain Symbol(n) for values and Symbol(n_R/_z) for derivatives (reduce_axisym.py)
names_in = {s_.name for s_ in L.free_symbols | Y.free_symbols}
assert names_in <= {j.name for j in jet} | {"R", "v_w"}, names_in - {
    j.name for j in jet
}
sym = {s_.name: s_ for s_ in L.free_symbols | Y.free_symbols}
jet = [sym.get(j.name, j) for j in jet]
R = sym.get("R", R)
vw = sym.get("v_w", vw)


def parts(expr, tag):
    g = [sp.diff(expr, q) for q in jet]
    H = {}
    for i in range(len(jet)):
        for j in range(i, len(jet)):
            hij = sp.diff(g[i], jet[j])
            if hij != 0:
                H[(i, j)] = hij
    print(
        f"{tag}: grad nonzero {sum(1 for x in g if x != 0)}/30, Hessian nonzero {len(H)} (upper)  [{time.time()-t0:.1f}s]",
        flush=True,
    )
    return g, H


gL, HL = parts(L, "Lrest")
gY, HY = parts(Y, "Y")
args = jet + [R, vw]
out = [
    '"""Generated by compile_local.py: per-cell derivatives of the axisymmetric D7 Lagrangian. Do not edit."""',
    "import numpy as np",
    "from numpy import sqrt",
    "",
    f"NJET = {len(jet)}",
    f"JET = {[j.name for j in jet]}",
    "",
]


def emit(name, exprs):
    # one function returning a list; cse keeps it compact
    reps, red = sp.cse(exprs, optimizations="basic")
    lines = [f"def {name}(q, R, v_w):"]
    lines += [f"    {j.name} = q[{k}]" for k, j in enumerate(jet)]
    for s_, e_ in reps:
        lines.append(f"    {s_} = {sp.pycode(e_)}")
    lines.append("    return [" + ", ".join(sp.pycode(e_) for e_ in red) + "]")
    return lines


keysL, keysY = sorted(HL), sorted(HY)
out += (
    emit("grad_L", gL)
    + [""]
    + emit("hess_L_vals", [HL[k] for k in keysL])
    + [""]
    + [f"HESS_L_KEYS = {keysL}", ""]
)
out += (
    emit("grad_Y", gY)
    + [""]
    + emit("hess_Y_vals", [HY[k] for k in keysY])
    + [""]
    + [f"HESS_Y_KEYS = {keysY}", ""]
)
out += emit("lagr_L", [L]) + [""] + emit("val_Y", [Y]) + [""]
src = "\n".join(out).replace("math.", "np.")
open("local_derivs.py", "w").write(src)
print(f"wrote local_derivs.py ({len(src)//1024} KB)  [{time.time()-t0:.1f}s]")
